// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJFDA0glSe3437WJ4L7AgM6mai_v3Tj2I',
    appId: '1:13230121115:web:3e95f8616ab6e3402e663e',
    messagingSenderId: '13230121115',
    projectId: 'employee-db-1b961',
    authDomain: 'employee-db-1b961.firebaseapp.com',
    databaseURL: 'https://employee-db-1b961-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-1b961.appspot.com',
    measurementId: 'G-0RPM2G74XM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyL62x8VBESfb6Rt44wjUSwJ5hYTE5JuM',
    appId: '1:13230121115:android:39ebe11a83bd9c512e663e',
    messagingSenderId: '13230121115',
    projectId: 'employee-db-1b961',
    databaseURL: 'https://employee-db-1b961-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-1b961.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_AfGbXAPjZTOV_sUyXm7PP1Eda-Zwzy0',
    appId: '1:13230121115:ios:fa2142189f9fc4e52e663e',
    messagingSenderId: '13230121115',
    projectId: 'employee-db-1b961',
    databaseURL: 'https://employee-db-1b961-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-1b961.appspot.com',
    iosBundleId: 'com.example.employee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_AfGbXAPjZTOV_sUyXm7PP1Eda-Zwzy0',
    appId: '1:13230121115:ios:fa2142189f9fc4e52e663e',
    messagingSenderId: '13230121115',
    projectId: 'employee-db-1b961',
    databaseURL: 'https://employee-db-1b961-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-1b961.appspot.com',
    iosBundleId: 'com.example.employee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJFDA0glSe3437WJ4L7AgM6mai_v3Tj2I',
    appId: '1:13230121115:web:0b1f5e03f06b5b9a2e663e',
    messagingSenderId: '13230121115',
    projectId: 'employee-db-1b961',
    authDomain: 'employee-db-1b961.firebaseapp.com',
    databaseURL: 'https://employee-db-1b961-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-1b961.appspot.com',
    measurementId: 'G-9LLVH05ER5',
  );

}